### ISSUE TITLE
Error when loading MoonlightR library

### ISSUE THREAD

**Issue by mona-n** [ibsquare/MoonlightR#4]
Dear all,

I receive the following error message when loading the Moonlight R library (version of MoonlightR is 1.12.0):

```
> library(MoonlightR)
Error: package or namespace load failed for 'MoonlightR':
 object 'TCGAanalyze_DMR' is not exported by 'namespace:TCGAbiolinks'
```

This error message only appears when I am using the newest version of TCGAbiolinks (version 2.14.1). However, when I use version 2.14.0 of TCGAbiolinks I do not receive the above error message when loading the MoonlightR library and the MoonlightR library is loaded succesfully. I have tried uninstalling the packages TCGAbiolinks (version 2.14.1) and MoonlightR and reinstalling them but that did not help. 

My version of R is 3.6.2 and Bioconductor version is 3.10. 

Thank you.
Best regards,
Mona Nourbakhsh

**Comment by torongs82** [comment]
Hi @mona-n  thank you for your feedback.

Regarding the TCGAanalyze_DMR from the package TCGAbiolinks.
As it was a differently methylated cpg (DMC) analysis instead of region analysis.
For that reason, we renamed it from TCGAanalyze_DMR to TCGAanalyze_DMC.

I suggest you this link https://github.com/BioinformaticsFMRP/TCGAbiolinks/issues/414
